# Generated by Django 2.2.14 on 2020-12-05 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('publicaciones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('publicaciones', models.ManyToManyField(related_name='tags', to='publicaciones.Publicacion')),
            ],
        ),
    ]
